### ISSUE TITLE
not starting bot

### ISSUE THREAD

**Issue by serverkur** [yannickgloster/discord-10man#118]
```
[DEBUG:10man.utils.csgo_server]: Created CSGO Server 0
[DEBUG:10man.cogs.utils]: Loaded cogs.utils
[DEBUG:10man.cogs.setup]: Loaded cogs.setup
[DEBUG:10man.utils.veto_image]: __initialise_assets
[DEBUG:10man.utils.veto_image]: __crop_map_images
[DEBUG:10man.utils.veto_image]: __add_map_name
[DEBUG:10man.cogs.csgo]: Loaded cogs.csgo
[INFO:10man.cogs.utils]: Checking for update.
[WARNING:10man.bot]: Stopping Bot
[WARNING:10man.utils.server]: Webserver Stopping on 10.0.2.8:39613
Traceback (most recent call last):
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 651, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 586, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MrPrincex\Desktop\discord-10man-master\run.py", line 11, in <module>
    discord_bot.run()
  File "C:\Users\MrPrincex\Desktop\discord-10man-master\bot.py", line 92, in run
    super().run(self.token, reconnect=True)
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 708, in run
    return future.result()
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 690, in runner
    await self.close()
  File "C:\Users\MrPrincex\Desktop\discord-10man-master\bot.py", line 88, in close
    await self.web_server.http_stop()
  File "C:\Users\MrPrincex\Desktop\discord-10man-master\utils\server.py", line 176, in http_stop
    await self.site.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000023FFC9289D0>
Traceback (most recent call last):
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\MrPrincex\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by serverkur** [comment]
Linux

`root@csgo:~/discord-10man-master# pipenv run python3 run.py
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    config = json.load(config_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 83 (char 84)`

**Comment by yannickgloster** [comment]
@yasuobey It looks like there is a problem with your json file, are you sure that you have it set up like this:
```json
{
    "discord_token": "123fkdjsh123alksjfhlaskdjafhlkj1hl3kj4hlkjss",
    "bot_IP": "",
    "bot_port": 3000,
    "steam_web_API_key": "123ABDKLK12938712938SBDDS1723987",
    "servers": [
        {
            "server_address": "csgo.yannickgloster.com",
            "server_port": 27015,
            "server_password": "pasword1234",
            "RCON_password": "1234password"
        }
    ]
}
```
Are there any special characters being used as well in the json?
Based on the logs, it looks like the discord intents aren't set correctly too. What have you set those too in the discord developer portal?

**Comment by serverkur** [comment]
I just don't have a password on my server and I left it empty

**Comment by yannickgloster** [comment]
Oh, did you put it like this?
```json
"server_password": "",
```

**Comment by serverkur** [comment]
```
{
    "discord_token": "NxxxxwXlFTWlrcbQFBrM",
    "bot_IP": "",
    "bot_port": 3066,
    "steam_web_API_key": "9D9CB9F82EBxxxxxx7D0F622D6F",
    "servers": [
        {
            "server_address": "3xxx132",
            "server_port": 27015,
            "server_password": "",
            "RCON_password": "xxx"
        }
    ]
}
```

**Comment by yannickgloster** [comment]
Try putting a space there and it might work. Didn't test that. I'll fix that bug tomorrow.

**Comment by serverkur** [comment]
So why am I getting a short error when I try it on my linux server?

`root@csgo:~/discord-10man-master# pipenv run python3 run.py
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    config = json.load(config_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 83 (char 84)`

**Comment by serverkur** [comment]
windows bot working 
linux not working (not solved)

password screenshot 👍 
![image](https://user-images.githubusercontent.com/36241002/100928386-2fe47580-34f7-11eb-9717-ab605c12f50f.png)
